export default Object.freeze({
  apiUrl: 'http://localhost:4000',
  genres: ['DOCUMENTARY',
    'COMEDY',
    'HORROR',
    'CRIME'],
  count: 30,
  movies: [
    {
      id: 1,
      photoUrl: 'https://www.film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/17155901-1124517.jpg',
      year: '2000',
      name: 'Name0',
      tagline: 'Some tagline',
      genres: [
        'Genre1', 'Genre2',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
    {
      id: 2,
      photoUrl: 'https://sun9-76.userapi.com/impf/GwWH0-c9_o4YdT4JGuXOvWhAFY41dLKG9xVxQA/H9CCEXSXj70.jpg?size=200x0&quality=90&sign=971314b1cae78fc73a59465d8b7ae6f4&ava=1',
      year: '2002',
      name: 'Name1',
      tagline: 'Some tagline',
      genres: [
        'Genre2', 'Genre3',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
    {
      id: 3,
      photoUrl: 'https://www.film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/43162181-1107473.jpg',
      year: '2001',
      name: 'Name2',
      tagline: 'Some tagline',
      genres: [
        'Genre1',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
    {
      id: 4,
      photoUrl: 'https://www.film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/17155901-1124517.jpg',
      year: '2000',
      name: 'Name3',
      tagline: 'Some tagline',
      genres: [
        'Genre1', 'Genre2',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
    {
      id: 5,
      photoUrl: 'https://sun9-76.userapi.com/impf/GwWH0-c9_o4YdT4JGuXOvWhAFY41dLKG9xVxQA/H9CCEXSXj70.jpg?size=200x0&quality=90&sign=971314b1cae78fc73a59465d8b7ae6f4&ava=1',
      year: '2002',
      name: 'Name4',
      tagline: 'Some tagline',
      genres: [
        'Genre2', 'Genre3',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
    {
      id: 6,
      photoUrl: 'https://www.film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/43162181-1107473.jpg',
      year: '2001',
      name: 'Name5',
      tagline: 'Some tagline',
      genres: [
        'Genre1',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
    {
      id: 7,
      photoUrl: 'https://www.film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/17155901-1124517.jpg',
      year: '2000',
      name: 'Name6',
      tagline: 'Some tagline',
      genres: [
        'Genre1', 'Genre2',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
    {
      id: 8,
      photoUrl: 'https://sun9-76.userapi.com/impf/GwWH0-c9_o4YdT4JGuXOvWhAFY41dLKG9xVxQA/H9CCEXSXj70.jpg?size=200x0&quality=90&sign=971314b1cae78fc73a59465d8b7ae6f4&ava=1',
      year: '2002',
      name: 'Name7',
      tagline: 'Some tagline',
      genres: [
        'Genre2', 'Genre3',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
    {
      id: 9,
      photoUrl: 'https://www.film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/43162181-1107473.jpg',
      year: '2001',
      name: 'Name8',
      tagline: 'Some tagline',
      genres: [
        'Genre1',
      ],
      voteAverage: 5.5,
      runtime: 120,
      overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    },
  ],
});
